# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "github-xcode-bot-builder"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ModCloth", "Two Bit Labs", "Geoffery Nix", "Todd Huss", "Banno"]
  s.date = "2014-05-20"
  s.description = "A command line tool that can be run via cron that configures and manages Xcode server bots for each pull request"
  s.email = ""
  s.executables = ["bot-sync-github", "bot-devices", "bot-status", "bot-delete"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/bot-delete",
    "bin/bot-devices",
    "bin/bot-status",
    "bin/bot-sync-github",
    "github-xcode-bot-builder.gemspec",
    "lib/bot_builder.rb",
    "lib/bot_cli.rb",
    "lib/bot_configuration.rb",
    "lib/bot_github.rb",
    "spec/github_xcode_bot_builder_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/ModCloth/github-xcode-bot-builder"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Create Xcode bots to run when github pull requests are created or updated"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<octokit>, ["~> 2.0"])
      s.add_runtime_dependency(%q<parseconfig>, ["~> 1.0.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<octokit>, ["~> 2.0"])
      s.add_dependency(%q<parseconfig>, ["~> 1.0.2"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<octokit>, ["~> 2.0"])
    s.add_dependency(%q<parseconfig>, ["~> 1.0.2"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
  end
end

